DROP TABLE CLIENTES;
DROP SEQUENCE SECUENCIA_CLIENTES;
DROP TABLE ACTIVIDADES;
DROP SEQUENCE SECUENCIA_ACTIVIDADES;
DROP TABLE MATRICULAS;

CREATE TABLE CLIENTES (
	ID INTEGER NOT NULL,
	DNI VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	TELEFONO INTEGER NOT NULL,
	ACTIVO INTEGER NOT NULL,
	TIPO INTEGER NOT NULL,
	PUNTOS INTEGER,
	PISCINA INTEGER, 
	PRIMARY KEY (ID),
	UNIQUE (DNI));

CREATE SEQUENCE SECUENCIA_CLIENTES
	INCREMENT BY 1
	START WITH 1;

CREATE TABLE ACTIVIDADES (
	ID INTEGER NOT NULL,
	NOMBRE VARCHAR(9) NOT NULL,
	DIA_SEMANA VARCHAR(30) NOT NULL,
	AFORO INTEGER NOT NULL,
	ACTIVO INTEGER NOT NULL,
	MATRICULADOS INTEGER NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (NOMBRE));

CREATE SEQUENCE SECUENCIA_ACTIVIDADES
	INCREMENT BY 1
	START WITH 1;
 
CREATE TABLE MATRICULAS (
	ID_CLIENTE INTEGER NOT NULL,
	ID_ACTIVIDAD INTEGER NOT NULL,
	PRIMARY KEY (ID_CLIENTE, ID_ACTIVIDAD),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID),
	FOREIGN KEY (ID_ACTIVIDAD) REFERENCES CLIENTES (ID));
 